// <auto-generated />
using System;
using Asesorias_API_MVC.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Asesorias_API_MVC.Migrations.AnalyticsDb
{
    [DbContext(typeof(AnalyticsDbContext))]
    [Migration("20251202044320_UpdateCalificacionSchema")]
    partial class UpdateCalificacionSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Asesorias_API_MVC.Models.AuditoriaAccion", b =>
                {
                    b.Property<int>("AuditoriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("AuditoriaId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AuditoriaId"));

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Accion");

                    b.Property<string>("Detalles")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Detalles");

                    b.Property<DateTime>("FechaAccion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("FechaAccion");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("UsuarioId");

                    b.HasKey("AuditoriaId");

                    b.ToTable("AuditoriaAcciones", (string)null);
                });

            modelBuilder.Entity("Asesorias_API_MVC.Models.Calificacion", b =>
                {
                    b.Property<int>("CalificacionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("CalificacionId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CalificacionId"));

                    b.Property<int>("AsesorId")
                        .HasColumnType("integer")
                        .HasColumnName("AsesorId");

                    b.Property<string>("Comentario")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Comentario");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedAt");

                    b.Property<int?>("CursoId")
                        .HasColumnType("integer")
                        .HasColumnName("CursoId");

                    b.Property<int>("EstudianteId")
                        .HasColumnType("integer")
                        .HasColumnName("EstudianteId");

                    b.Property<int>("Rating")
                        .HasColumnType("integer")
                        .HasColumnName("Rating");

                    b.Property<int?>("SolicitudId")
                        .HasColumnType("integer")
                        .HasColumnName("SolicitudId");

                    b.HasKey("CalificacionId");

                    b.ToTable("Calificaciones", (string)null);
                });

            modelBuilder.Entity("Asesorias_API_MVC.Models.HistorialPago", b =>
                {
                    b.Property<int>("PagoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("PagoId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PagoId"));

                    b.Property<string>("CorreoFacturacion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("CorreoFacturacion");

                    b.Property<int>("CursoId")
                        .HasColumnType("integer")
                        .HasColumnName("CursoId");

                    b.Property<int>("EstudianteId")
                        .HasColumnType("integer")
                        .HasColumnName("EstudianteId");

                    b.Property<DateTime>("FechaPago")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("FechaPago");

                    b.Property<string>("MetodoPago")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("MetodoPago");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("Monto");

                    b.HasKey("PagoId");

                    b.ToTable("HistorialDePagos", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
